apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: scm
spec:
  selector:
    app: git-server
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: git
    port: 9418